"""add gateway fields to payments

Revision ID: 0da7d0b3ebcb
Revises: 000adfedb0da
Create Date: 2026-04-22 16:55:24.869857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da7d0b3ebcb'
down_revision: Union[str, Sequence[str], None] = '4f4145d5df67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('gateway_transaction_id', sa.String(length=200), nullable=True))
    op.add_column('payments', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('payment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_url')
    op.drop_column('payments', 'phone_number')
    op.drop_column('payments', 'gateway_transaction_id')
    # ### end Alembic commands ###
