"""create packages and bookings tables

Revision ID: 8c8969bfa5a1
Revises: 2f892e76915b
Create Date: 2026-03-15 04:27:25.999687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8969bfa5a1'
down_revision: Union[str, Sequence[str], None] = '2f892e76915b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', 'removed', name='experience_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['cultural_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiences_created_at', 'experiences', ['created_at'], unique=False)
    op.create_index('ix_experiences_location', 'experiences', ['location'], unique=False)
    op.create_index('ix_experiences_provider_id', 'experiences', ['provider_id'], unique=False)
    op.create_index('ix_experiences_status', 'experiences', ['status'], unique=False)
    op.create_index('ix_experiences_status_created_at', 'experiences', ['status', 'created_at'], unique=False)
    op.create_table('packages',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('includes_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', 'cancelled', name='package_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['cultural_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_packages_created_at', 'packages', ['created_at'], unique=False)
    op.create_index('ix_packages_event_date', 'packages', ['event_date'], unique=False)
    op.create_index('ix_packages_provider_id', 'packages', ['provider_id'], unique=False)
    op.create_index('ix_packages_provider_status', 'packages', ['provider_id', 'status'], unique=False)
    op.create_index('ix_packages_status', 'packages', ['status'], unique=False)
    op.create_index('ix_packages_status_event_date', 'packages', ['status', 'event_date'], unique=False)
    op.create_table('bookings',
    sa.Column('tourist_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('booking_status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='booking_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'pending', 'paid', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('package_title_snapshot', sa.String(length=200), nullable=False),
    sa.Column('provider_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('event_date_snapshot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_booking_date', 'bookings', ['booking_date'], unique=False)
    op.create_index('ix_bookings_booking_status', 'bookings', ['booking_status'], unique=False)
    op.create_index('ix_bookings_package_booking_date', 'bookings', ['package_id', 'booking_date'], unique=False)
    op.create_index('ix_bookings_package_id', 'bookings', ['package_id'], unique=False)
    op.create_index('ix_bookings_payment_status', 'bookings', ['payment_status'], unique=False)
    op.create_index('ix_bookings_tourist_booking_date', 'bookings', ['tourist_id', 'booking_date'], unique=False)
    op.create_index('ix_bookings_tourist_id', 'bookings', ['tourist_id'], unique=False)
    op.create_table('experience_comments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experience_comments_created_at', 'experience_comments', ['created_at'], unique=False)
    op.create_index('ix_experience_comments_experience_created', 'experience_comments', ['experience_id', 'created_at'], unique=False)
    op.create_index('ix_experience_comments_experience_id', 'experience_comments', ['experience_id'], unique=False)
    op.create_index('ix_experience_comments_user_id', 'experience_comments', ['user_id'], unique=False)
    op.create_table('experience_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'experience_id', name='uq_experience_like_user_experience')
    )
    op.create_index('ix_experience_likes_experience_id', 'experience_likes', ['experience_id'], unique=False)
    op.create_index('ix_experience_likes_user_id', 'experience_likes', ['user_id'], unique=False)
    op.create_table('experience_media',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='experience_media_type'), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('media_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experience_media_experience_id', 'experience_media', ['experience_id'], unique=False)
    op.create_index('ix_experience_media_media_order', 'experience_media', ['media_order'], unique=False)
    op.create_table('package_media',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('media_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_package_media_media_order', 'package_media', ['media_order'], unique=False)
    op.create_index('ix_package_media_package_id', 'package_media', ['package_id'], unique=False)
    op.create_table('booking_participants',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('participant_name', sa.String(length=150), nullable=False),
    sa.Column('participant_email', sa.String(length=255), nullable=True),
    sa.Column('participant_phone', sa.String(length=30), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_participants_booking_id', 'booking_participants', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_participants_booking_id', table_name='booking_participants')
    op.drop_table('booking_participants')
    op.drop_index('ix_package_media_package_id', table_name='package_media')
    op.drop_index('ix_package_media_media_order', table_name='package_media')
    op.drop_table('package_media')
    op.drop_index('ix_experience_media_media_order', table_name='experience_media')
    op.drop_index('ix_experience_media_experience_id', table_name='experience_media')
    op.drop_table('experience_media')
    op.drop_index('ix_experience_likes_user_id', table_name='experience_likes')
    op.drop_index('ix_experience_likes_experience_id', table_name='experience_likes')
    op.drop_table('experience_likes')
    op.drop_index('ix_experience_comments_user_id', table_name='experience_comments')
    op.drop_index('ix_experience_comments_experience_id', table_name='experience_comments')
    op.drop_index('ix_experience_comments_experience_created', table_name='experience_comments')
    op.drop_index('ix_experience_comments_created_at', table_name='experience_comments')
    op.drop_table('experience_comments')
    op.drop_index('ix_bookings_tourist_id', table_name='bookings')
    op.drop_index('ix_bookings_tourist_booking_date', table_name='bookings')
    op.drop_index('ix_bookings_payment_status', table_name='bookings')
    op.drop_index('ix_bookings_package_id', table_name='bookings')
    op.drop_index('ix_bookings_package_booking_date', table_name='bookings')
    op.drop_index('ix_bookings_booking_status', table_name='bookings')
    op.drop_index('ix_bookings_booking_date', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_packages_status_event_date', table_name='packages')
    op.drop_index('ix_packages_status', table_name='packages')
    op.drop_index('ix_packages_provider_status', table_name='packages')
    op.drop_index('ix_packages_provider_id', table_name='packages')
    op.drop_index('ix_packages_event_date', table_name='packages')
    op.drop_index('ix_packages_created_at', table_name='packages')
    op.drop_table('packages')
    op.drop_index('ix_experiences_status_created_at', table_name='experiences')
    op.drop_index('ix_experiences_status', table_name='experiences')
    op.drop_index('ix_experiences_provider_id', table_name='experiences')
    op.drop_index('ix_experiences_location', table_name='experiences')
    op.drop_index('ix_experiences_created_at', table_name='experiences')
    op.drop_table('experiences')
    # ### end Alembic commands ###
