"""add booking pricing breakdown and gateway ready payment flow

Revision ID: 959c1442f6f4
Revises: a3da6bc3e7f2
Create Date: 2026-04-07 16:22:29.401490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '959c1442f6f4'
down_revision: Union[str, Sequence[str], None] = 'a3da6bc3e7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ── base_price ──
    op.add_column('bookings', sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute("UPDATE bookings SET base_price = 0 WHERE base_price IS NULL")
    op.alter_column('bookings', 'base_price', nullable=False)

    # ── platform_fee ──
    op.add_column('bookings', sa.Column('platform_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute("UPDATE bookings SET platform_fee = 0 WHERE platform_fee IS NULL")
    op.alter_column('bookings', 'platform_fee', nullable=False)

    # ── provider_payout_amount ──
    op.add_column('bookings', sa.Column('provider_payout_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute("UPDATE bookings SET provider_payout_amount = 0 WHERE provider_payout_amount IS NULL")
    op.alter_column('bookings', 'provider_payout_amount', nullable=False)
    

    # ── currency ──
    op.add_column('bookings', sa.Column('currency', sa.Numeric(precision=10), nullable=True))
    op.execute("UPDATE bookings SET currency = 0 WHERE currency IS NULL")
    op.alter_column('bookings', 'currency', nullable=False)


    op.alter_column('bookings', 'payment_status',
               existing_type=postgresql.ENUM('unpaid', 'pending', 'paid', 'failed', 'refunded', name='payment_status'),
               type_=sa.Enum('unpaid', 'pending', 'paid', 'failed', 'refunded', name='payment_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'payment_status',
               existing_type=sa.Enum('unpaid', 'pending', 'paid', 'failed', 'refunded', name='booking_payment_status'),
               type_=postgresql.ENUM('unpaid', 'pending', 'paid', 'failed', 'refunded', name='payment_status'),
               existing_nullable=False)
    op.drop_column('bookings', 'currency')
    op.drop_column('bookings', 'provider_payout_amount')
    op.drop_column('bookings', 'platform_fee')
    op.drop_column('bookings', 'base_price')
    # ### end Alembic commands ###
