"""add experience_views table

Revision ID: b9a2df24d4f1
Revises: 532e834f63c8
Create Date: 2026-04-24 16:47:52.382690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a2df24d4f1'
down_revision: Union[str, Sequence[str], None] = '532e834f63c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_views',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('watch_seconds', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experience_views_experience_id', 'experience_views', ['experience_id'], unique=False)
    op.create_index('ix_experience_views_session_id', 'experience_views', ['session_id'], unique=False)
    op.create_index('ix_experience_views_viewer_user_id', 'experience_views', ['viewer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_experience_views_viewer_user_id', table_name='experience_views')
    op.drop_index('ix_experience_views_session_id', table_name='experience_views')
    op.drop_index('ix_experience_views_experience_id', table_name='experience_views')
    op.drop_table('experience_views')
    # ### end Alembic commands ###
