"""site follow and provider management updates

Revision ID: dd11a3729db9
Revises: e6035e1a4013
Create Date: 2026-03-17 15:17:03.811570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd11a3729db9'
down_revision: Union[str, Sequence[str], None] = 'e6035e1a4013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_follows',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['cultural_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'site_id', name='uq_site_follows_user_site')
    )
    op.create_index('ix_site_follows_site_id', 'site_follows', ['site_id'], unique=False)
    op.create_index('ix_site_follows_user_id', 'site_follows', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_follows_user_id', table_name='site_follows')
    op.drop_index('ix_site_follows_site_id', table_name='site_follows')
    op.drop_table('site_follows')
    # ### end Alembic commands ###
